### ISSUE TITLE
Can't input data?

### ISSUE THREAD

**Issue by rstarmer** [CiscoSystems/cognitive#22]
Selected train.csv from temp folder to try system.  System doesn't respond to the add button (does respond to the file selection, just not add).

**Comment by johnugeorge** [comment]
can you provide the browser details?

**Comment by travelist** [comment]
@rstarmer  Thanks for reporting issues. We will check the code and behavior soon. If you provides some details to reproduce the same errors, it will help us. and also if you have some opinions to improve  current UI behaviors, it's greatly appreciated. thank you!

**Comment by johnugeorge** [comment]
It looks like you haven't created workspace before adding the input source. Validation is missing from UI. Each user can multiple workspace(or experiments) at the same time. So , can you try creating a workspace first and then try again?  I will add it in the README

**Comment by rstarmer** [comment]
Certainly it was a lack of workspace that caused my issue.  Perhaps a UI
warning if one doesn't exist?

Thanks!
Robert


Robert

**Comment by travelist** [comment]
@rstarmer thank you for informing us. We will fix with this issue to make default workspace when user logged in. Thanks again!:)

**Comment by rstarmer** [comment]
Sounds good

Robert
