### ISSUE TITLE
UI doesn't make it obvious when a manual input vs. selection is available

### ISSUE THREAD

**Issue by rstarmer** [CiscoSystems/cognitive#23]
When selecting a capability from the list (e.g. "math formula"), it's not clear that selections are pulldown lists.  This looks like a simple UX glitch.

**Comment by travelist** [comment]
@rstarmer thanks for comment. I agree with you. that design will be improved soon to easily understand which is the pull down and the other as well. thanks!:)

**Comment by johnugeorge** [comment]
Add default selection for the each drop down

**Comment by rstarmer** [comment]
Great!

Robert
