### ISSUE TITLE
Need CI environment

### ISSUE THREAD

**Issue by travelist** [CiscoSystems/cognitive#31]
Let's use travis CI or Circle CI or Jenkins as a CI environment.
To enable travis CI for example, one has the rights to manage this repository have to activate travis service. after that, we can add .travis.yml file.

**Comment by ddutta** [comment]
Agree!

**Comment by travelist** [comment]
@ddutta thank you! perhaps travis ci is the easy way to cooperate. (I think just click 'sync' or something after login to travis-ci service using github account. after that, I will put .travis.yml file on this repository)

**Comment by ddutta** [comment]
done .... now you can put the travis.yml

**Comment by travelist** [comment]
@ddutta so fast!! I really thank you:)

**Comment by ddutta** [comment]
you still have to go to travis-ci.org .... sign in with github credentials,
enable cognitive (I did and ensured ciscosystems didn't have 3rd party
restrictions)

On Wed, May 27, 2015 at 10:41 PM, Komei Shimamura <notifications@github.com>
wrote:

> @ddutta <https://github.com/ddutta> so fast!! I really thank you:)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CiscoSystems/cognitive/issues/31#issuecomment-106181222>
> .
>



-- 
-Debo~

**Comment by travelist** [comment]
@ddutta for me, travis-ci requires me to have admin rights for CiscoSystems/cognitive repository...
I added .travis.yml file to develop branch of cognitive, so some log file should be appeared here (https://travis-ci.org/CiscoSystems/cognitive/) if it works correctly. will confirm later again
