### ISSUE TITLE
Import Error: No module named django.core.management

### ISSUE THREAD

**Issue by Njreardo** [CiscoSystems/cognitive#32]
Can't run the server without django.core.management

**Comment by travelist** [comment]
@Njreardo Thanks for reporting issues. if it's fine, would you push the pull request for us?

**Comment by Njreardo** [comment]
I downloaded the zip. Should I push it to my github account?

**Comment by travelist** [comment]
@Njreardo We reproduced the same issue.it seems to come from the failure of some other package installation stops the entire pip installation process. we will investigate more and fix this problem:)
if you have some idea, it's greatly appreciated:)
------
to Push the code, click the Fork button on the right top of the SyscoSystems/cognitive, and your account can get your cognitive fork repository. after that, you can clone from your cognitive, and commit the changes, and then you can make pull requests from your cognitive repo to our repo. 
thanks again!:)

**Comment by Njreardo** [comment]
Thanks! It looks like an amazing program and I can't wait to use it! I've tried Azure ML Studio, and it looks just like that. I'm a Data Scientist so anything that comes out like this really excites me! If I may ask a favor though, please post here when the issue is solved.

**Comment by travelist** [comment]
@Njreardo We fixed the issue. so you can try now. thank you for reporting issues. Cognitive is  still in development, so when you face some other problem or some required features, let us know. it's really appreciated too. thanks!:)
